### ISSUE TITLE
Error compiling with React v17 and react-scripts v3

### ISSUE THREAD

**Issue by jacobogart** [tatethurston/react-use-error-boundary#13]
Error: 
```
Failed to compile.

./node_modules/react-use-error-boundary/module/index.js 4:15
Module parse failed: Unexpected token (4:15)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| class ReactUseErrorBoundaryWrappedError extends Error {
>   originalError;
| 
|   constructor(error) {
```

Application Versions:
"react": "^17.0.2"
"react-scripts": "3.4.4"

Let me know if this looks like user error an if there are any suggestions for additional loaders that could resolve this issue. Thanks!

**Comment by jacobogart** [comment]
After the following steps, I received a slightly different error:
1. Update "development" "browserslist to: ` [ ">0.2%", "not dead", "not op_mini all"]`
2. Run `yarn cache clean`
3. Run `rm -rf node_modules && rm -f yarn.lock && yarn install`

New error:

```
Failed to compile.

./node_modules/react-use-error-boundary/module/index.js
SyntaxError: /Users/P2911346/Charter/aloha-ui/node_modules/react-use-error-boundary/module/index.js: Missing class properties transform.
  1 | import React, { Component, useState, useCallback, createContext, useContext, useMemo, useRef, } from "react";
  2 | class ReactUseErrorBoundaryWrappedError extends Error {
> 3 |     originalError;
    |     ^^^^^^^^^^^^^^
  4 |     constructor(error) {
  5 |         console.warn("react-use-error-boundary: A value was thrown that is not an instance of Error. Thrown values should be instantiated with JavaScript's Error constructor.");
  6 |         try {
  ```

**Comment by jacobogart** [comment]
Did some messing around and after removing [Line 33](https://github.com/tatethurston/react-use-error-boundary/blob/main/src/index.tsx#L33) and [Line 64](https://github.com/tatethurston/react-use-error-boundary/blob/main/src/index.tsx#L64) from the index file, I was able to compile without errors and got the desired functionality. Are these lines necessary, and could they be removed if not?

**Comment by tatethurston** [comment]
@jacobogart This is because this package's source code is using language features that are more recent than your build configuration supports, specifically related to class properties. 

Some options:
1. I could transpile the distributed source code to an older JavaScript target
2. You could update your build configuration to transpile more modern JavaScript (this would be updating your version of react-scripts, which is outdated, the most recent version is 5.0.1).
3. I could alter the package code using more modern language features.

I have been planning to remove the error wrapping runtime that was introduced in v2, so I've gone ahead and done that in v3. If you update to v3 of this package, things should work for you without changing anything. Let me know if not!
